// Session data for the world

export const sessions = [
  {
    id: 'session-11',
    title: 'Session 11',
    subtitle: 'Inside the Ball',
    date: 'December 14, 2025',
    upcoming: true,
    description: 'The party has infiltrated the Grand Duke\'s ball as the Whitaker brothers. With their cover intact but danger implied, the night is officially underway.',
    highlights: [],
  },
  {
    id: 'session-10',
    title: 'Session 10',
    subtitle: 'The Brothers Whitaker',
    date: 'November 16, 2025',
    upcoming: false,
    summaryFile: 'session-10.md',
    description: 'A new ally emerges as Lord Whitaker the 6th ("Witty") joins the party. After securing lodging at the Golden Goose and acquiring funds from Nyx\'s townhouse, the group devises a plan to infiltrate the Grand Duke\'s ball by impersonating the Whitaker brothers. Ellara attends as Proctor Eduard\'s guest, while Berridin, Nyx, and Ysidor pose as Whitakers 3-5. The ball celebrates Lady Ophelia\'s return from Torchlight College, and the party successfully enters—though Donnathan Reeves greets "Orange" with dangerous familiarity.',
    highlights: [
      'Ellara receives a formal invitation to the Grand Duke\'s ball from Proctor Eduard.',
      'Nyx books a room at the Golden Goose hotel with a sickle as collateral.',
      'Lord Whitaker the 6th ("Witty") is introduced—an eccentric noble seeking lighthouse connections.',
      'Berridin and Ysidor raid Nyx\'s cache for 82 gold; Nyx threatens consequences.',
      'Witty invents "Success Gas"—snake venom and sphinx glands—affecting Ysidor and Berridin.',
      'The party adopts Whitaker brother identities: Berridin as #3 (Orange), Nyx as #4 (Brown), Ysidor as #5 (Yellow).',
      'Lady Ophelia Xanteres Oleander, the Grand Duke\'s niece and heir, is the guest of honor.',
      'Ellara arrives with Eduard and is introduced to the Duke, Reeves, and Ophelia.',
      'Ophelia hints at army delays at a mining town before being redirected.',
      'Donnathan Reeves greets the "Whitaker brothers" with suspicion about #3\'s return from exile.',
    ],
  },
  {
    id: 'session-9',
    title: 'Session 9',
    subtitle: 'The Golden Dove and the Sickly Son',
    location: 'Bastion City',
    date: 'November 2, 2025',
    time: '1:00 PM',
    upcoming: false,
    summaryFile: 'session-9.md',
    description: 'The party splits to gather intelligence on Donnathan Reeves. Nyx and Ysidor infiltrate the Civic Hall of Records, leading to Ysidor\'s accidental "abduction" by a well-meaning noblewoman. Meanwhile, Ellara and Berridin scout the Ducal Palace and uncover a high-end tavern that becomes central to their cover story.',
    highlights: [
      'Party rendezvous at Badwater Well; Nyx is paranoid but eventually confirms safety.',
      'Nyx and Ysidor adopt disguises "Alexander" and "Elk" to visit the Civic Hall of Records.',
      'Ysidor (as "Elk") is "rescued" by Lady Jacinta, who mistakes his disguise for a terrible illness.',
      'Nyx retrieves Reeves\' address (Viscount Sommeil\'s estate) but learns he stays at the Palace.',
      'Lady Jacinta reveals it is an "open secret" that Reeves and Grand Duke Oleander are lovers.',
      'Nyx lies to Jacinta about staying at "The Golden Dove" to maintain cover.',
      'Ellara and Berridin scout the Palace and enter The Golden Dove tavern.',
      'Berridin overhears rumors of a Ball for the Duke\'s "returned friend".',
      'Ellara confirms with Guard Diane that Proctor Eduard attends these functions.',
      'Nyx realizes he must now book a room at The Golden Dove to support his lie.'
    ],
  },
  {
    id: 'session-8',
    title: 'Session 8',
    subtitle: 'The Screaming Lamp',
    location: 'Seminary & Bastion Streets',
    date: 'October 19, 2025',
    time: '1:00 PM',
    upcoming: false,
    summaryFile: 'session-8.md',
    description: 'Ellara meets Director Reeves and learns of the deep connections between Proctor Eduard, the Lighthouse, and the imperial nobility. Her vision of a screaming lamp leads to a moral reckoning about light crystals. Meanwhile, the party\'s botched reconnaissance at the Lighthouse leaves their rune passes compromised and forces them to scatter across the city.',
    highlights: [
      'Proctor Eduard revealed as fifth son of Marchioness of Marchenbau with connections to Empress Consort',
      'Director Reeves confirmed as Viscount Sommeil and old college friend of Grand Duke Valerian Oleander',
      'Ellara\'s vision of the screaming lamp represents the suffering of all Shadowed in light crystals',
      'Failed Lighthouse reconnaissance: party\'s rune passes compromised, alarms triggered',
      'Chaotic forecourt battle with warforged and guards as party attempts escape',
      'Berridin and Ysidor flee together using mirror images and bardic inspiration',
      'Nyx uses Blessing of the Raven Queen to teleport to safety',
      'Party scatters with rendezvous set at Badwater Well',
      'Internal trust frayed as Ellara catches Berridin lying about the mission'
    ],
  },
  {
    id: 'session-7',
    title: 'Session 7',
    subtitle: 'Crossroads at Dawn',
    location: 'Bastion Outskirts & City',
    date: 'September 21, 2025',
    time: '1:00 PM',
    upcoming: false,
  description: 'After rescuing Meri, the party shelters in an abandoned barn where she reveals the full truth: Proctor Eduard himself operated the synthesis machine on her as part of a plan to suppress her people and seize their land for light crystal mining. A rift forms as Ysidor feels duty-bound to return to his village, Hýrda, while Ellara and Nyx argue they must stay to fight the conspiracy at its source. Ultimately, Ysidor agrees to stay for one month. The party returns to Bastion to find security heightened with new warforged, and Ellara comes face-to-face with both Eduard and his political liaison, Donnathan Reeves.',
    summaryFile: 'session-7.md',
    highlights: [
      'Meri reveals Proctor Eduard personally operated the synthesis machine on her.',
      'The motive for the experiments is revealed: to clear the way for imperial mining of light crystals in Hýrda, Meri\'s village.',
      'A tense party debate leads to a split: Meri departs for Hýrda, while the others return to Bastion to confront Eduard.',
      'Nyx reveals he is also Shadowed, declaring he will not be turned into a "light bulb."',
      'Ysidor commits to staying in Bastion for one month to help before returning to his people.',
      'New-model warforged are seen on patrol at the East Gate and the Lighthouse, indicating a security increase.',
      'Proctor Eduard introduces Ellara to Donnathan Reeves, the Director of Relations at the Lighthouse, connecting the two main conspirators.',
      'The party uses sending stones to maintain communication after splitting up.'
    ],
  },
  {
    id: 'session-6',
    title: 'Session 6',
    subtitle:'Descent into Darkness',
    location: 'Duskbreaker Lighthouse',
    date: 'September 7, 2025',
    time: '1:00 PM',
    upcoming: false,
    description: 'A two-pronged infiltration puts Berridin (as “Director Faberge”) in the basement lab where he finds Meri alive, a subject in the Lighthouse\'s synthetic light-crystal program that consumes Shadowed beings. He freezes the run, moves her to Med Bay, and triggers a one-shot Dimension Door rune to extract her to the front steps as alarms erupt, while Nyx maintains cover, Ellara uncovers Faberge\'s notes, and Ysidor carries Meri to safety. The party escapes to an old growth outside the city with Meri stable but unconscious and leads implicating Eulogian liaison Donnathan Reeves.',
    summaryFile: 'session-6.md',
    highlights: [
      'Berridin, disguised as Director Faberge, accessed the basement lab and found Meri alive and shackled as a test subject.',
      'Dawn revealed the Lighthouse synthesizes light crystals by consuming Shadowed beings; “alive at initiation” yields the best results; Meri was at 15% with a furnace step planned next.',
      'Processed crystals go upstairs to current projects; found crystals from Shadowed ruins suffer cross-contamination.',
      'Eulogian liaison Donnathan Reeves was named as the one who delivers subjects “per protocol.”',
      'Berridin halted the run, ordered a move to Med Bay, and used a one-shot Dimension Door rune to extract Meri to the lighthouse steps.',
      'Nyx kept his cover as guard “Stanley” and ghosted out during the alarm.',
      'Ellara infiltrated Faberge\'s workshop (via spider wild shape), uncovering a shared power bottleneck and the single-use Dimension Door rune; she took detailed notes and an uncharged spare.',
      'Ysidor performed an Atonement rite for Stanley and later carried Meri during the escape; Ellara confirmed Meri is stable and just needs rest.',
      'The party regrouped under an old growth tree outside Bastion City as alarms rang across the Lighthouse.',
      'Tsi\'Nyra silently connected the “two floral” prior subjects to her sisters; Nyx noticed and let it be; Ellara rejected the implication of Eulogian complicity without proof.',
    ],
  },
  {
    id: 'session-5',
    title: 'Session 5',
    subtitle: 'Into the Lighthouse',
    location: 'Bastion City',
    date: 'August 31, 2025',
    time: '1:30 PM',
    upcoming: false,
    description: 'After surviving the warforged ambush, the party investigates the trap site and discovers the constructs bear Duskbreaker Lighthouse insignia. They return to Bastion City where Ellara consults Proctor Eduard, who reveals the lighthouse\'s involvement and promises an official investigation. Meanwhile, Tsi\'Nyra\'s spider familiar scouts the lighthouse, uncovering extensive underground facilities. Faced with divine guidance, Ellara decides to join the party in infiltrating the lighthouse to find the truth about Meri.',
    summaryFile: 'session-5.md',
    highlights: [
      'Nyx kills Director of Research Michelle Faberge during a botched pursuit, creating a moral crisis for Ellara.',
      'Berridin successfully infiltrates the lighthouse disguised as the deceased Director using her security pass.',
      'Nyx gains entry as "Stanley," a guard with substance abuse issues, and maps internal security protocols.',
      'The party discovers the lighthouse\'s multi-tier warforged development program including titan-scale constructs.',
      'Research reveals phosphorus additives can increase crystal capacity tenfold, enabling 24/7 warforged operation.',
      'Director of Relations Donnathan Reeves is in Pharos liaising with Eulogians, revealing political dimensions.',
      'Ellara performs last rites for Faberge after meeting artificer Darius, who mentions his missing colleague.',
      'The party acquires critical assets: Director and guard security passes, sending stones, and prototype devices.',
      'Internal lighthouse documents use invisible ink, suggesting hidden layers of information.',
      'Ysidor and Tsi\'Nyra incapacitate a guard through an elaborate drinking contest, preventing him from reporting to duty.',
    ],
  },
  {
    id: 'session-4',
    title: 'Session 4',
    subtitle: 'Questions in the Crystal Light',
    location: 'Bastion City Outskirts',
    date: 'July 20, 2025',
    time: '10:00 AM',
    upcoming: false,
    description: 'After surviving the warforged ambush, the party investigates the trap site and discovers the constructs bear Duskbreaker Lighthouse insignia. They return to Bastion City where Ellara consults Proctor Eduard, who reveals the lighthouse\'s involvement and promises an official investigation. Meanwhile, Tsi\'Nyra\'s spider familiar scouts the lighthouse, uncovering extensive underground facilities. Faced with divine guidance, Ellara decides to join the party in infiltrating the lighthouse to find the truth about Meri.',
    summaryFile: 'session-4.md',
    highlights: [
      'Investigation of the trap site reveals no trace of Meri and confirms the warforged were made by Duskbreaker Lighthouse.',
      'Nyx collects three light crystals from the destroyed constructs as evidence.',
      'Ellara reports the encounter to Proctor Eduard, who expresses genuine shock and promises to escalate to the Eulogia.',
      'Eduard reveals tensions between the lighthouse and the Eulogia, claiming they are "blinded by their own ambition."',
      'Tsi\'Nyra\'s spider familiar discovers the lighthouse has extensive underground facilities with strange metalwork and noises.',
      'Ellara receives divine guidance through meditation confirming she should help investigate the lighthouse.',
      'The party decides to infiltrate the Duskbreaker Lighthouse to find evidence about Meri and the conspiracy.',
      'Nyx reluctantly reveals his townhouse to the party, showcasing his anxiety about privacy and his culinary disasters.',
    ],
  },
  {
    id: 'session-3',
    title: 'Session 3',
    subtitle: 'Confronting the Proctor',
    date: 'June 22, 2025',
    time: '1:00 PM', // Added time
    location: 'Bastion City', // Added location
    upcoming: false,
    description: 'The party confronts Proctor Eduard at the seminary and secures Meri’s release, shares camaraderie at The Drunken Goose, sets out by carriage at dawn, survives an ambush by warforged powered by light crystals, and uncovers clues to the mastermind behind the trap.',
    summaryFile: 'session-3.md',
    highlights: [
      'Confrontation at the Eulogian Seminary and discovery that Meri was released.',
      'Colorful downtime at the Drunken Goose tavern revealing character bonds and humor.',
      'Ellara’s ritual and theological probe reveal cryptic counsel from Proctor Eduard.',
      'Group reunion at the East Gate and plans for a mounted pursuit.',
      'Ambush by three warforged constructs powered by light crystals.',
      'Tactical battle with no party casualties and dramatic finishing moves.',
      'Investigation uncovers constructs were laid as a trap using Bastion City light technology.',
      'Lingering questions about the mastermind behind the ambush and the shadow connection.',
    ],
  },
  {
    id: 'session-2',
    title: 'Session 2',
    subtitle: 'Dreams in the Shadow of the Light',
    date: 'Jun 08, 2025',
    upcoming: false,
    description: 'The session begins with the PCs experiencing vivid dreams. Morning activities lead to new information for Ellara about Nyx and Meri. The party then ventures into West Bastion, investigating two prisons to find Ysidor\'s mentor, Meri. They discover that Meri was transferred under the personal custody of Proctor Eduard, deepening the mystery.',
    summaryFile: 'session-2.md',
    highlights: [
      'Each character experiences vivid, revealing, or unsettling dreams, including Ysidor\'s memory of Meri and Ellara hearing foreign words of Eulogia.',
      'Tsi\'Nyra joyfully discovers "breakfast!" at Nyx\'s townhouse, experimenting with various food combinations.',
      'At the Eulogian Seminary, Ellara learns from the Denmother that Nyx is known as a "fixer" and that Meri was moved to a "western" prison.',
      'Proctor Eduard expresses disdain for goliaths, to which Ellara offers a diplomatic rebuttal.',
      'Berridin disguises Ysidor as a tall human named "Moose" for their trip to West Bastion.',
      'The party, including a wide-eyed Tsi\'Nyra and "Moose," gets their first look at the opulent West Bastion.',
      'After a failed bribery attempt at the first prison, Nyx successfully bribes a guard at Stonewall Tower for information.',
      'Berridin cleverly uses Invisibility to slip past guards and discover a ledger entry: "Custody Transfer—His Holy Eminence Proctor Eduard."',
      'A tense confrontation with a Stonewall Tower guard, who warns Ellara about "people much higher" pulling strings, hints at deeper mysteries.',
      'The party confirms Meri was transferred under the personal custody of Proctor Eduard, directly implicating him leaving Ellaria stunned.',
    ],
  },
  {
    id: 'session-1',
    title: 'Session 1',
    subtitle: 'The Adventure Begins',
    date: 'May 18, 2025',
    upcoming: false,
    description: 'Set in the year 651 AE (After Eulogia) in Bastion City, the capital of Hieroterra Province. The party begins their journey in this divided city where the East and West sides represent stark contrasts in wealth and influence. Mysterious disappearances, including that of a powerful goliath, set the stage for the campaign\'s first major storyline.',
    summaryFile: 'session-1.md',
    highlights: [
      'Introduced Bastion City and the political landscape of Hieroterra Province under Duke Valerian Oleander.',
      'Established the East-West divide of the city, with the West being affluent and the East more modest, featuring the Duskbreaker Lighthouse.',
      'Tsi\'Nyra arrived at Nyx\'s at her mother\'s request searching for her missing sisters.',
      'Ellara encountered Berridin and later Ysidor during Alm\'s Giving in the Eastern City.',
      'After a commotion when Tsi\'Nyra and Nyx arrived Ellara took the group aside.',
      'Ellara felt like this connection was meant to be and she was supposed to help desipte the Shadowed in the group',
      'Ysidor asked about his mentor, Meri, who was missing. Ellara mentioned she was likely imprisoned after an incident where she took down 20 guards and shouted about the Lighthouse.',
      'Berridin and Ysidor visited the Halfling Quarter, where Berridin showed his connection to the community. The Candy Incident of 650 AE was mentioned.',
      'Ellara asked her the Denmother about Meri who was likely imprisoned.',
      'Nyx gathered intelligence at a seedy bar from a guard about Meri and learned she was moved from the Eastern prison to one in the West.',
      'The party agreed to meet in 2 days to discuss their next steps.',
    ]
  },
  {
    id: 'session-0',
    title: 'Session 0',
    subtitle: 'Character Creation',
    date: 'May 4, 2025',
    upcoming: false,
    description: 'Character creation and world introduction. Come prepared with character concepts and backstory ideas based on Session -1!',
    highlights: [
      'Provided an overview of the world setting.',
      'Discussed the history of Eulogia.',
      'Gave a brief overview of key locations.',
      'Discussed differences between D&D 5e 2014 and 2024 rulesets for character creation.',
      'Compared Point Buy and Standard Array methods for ability scores and decided to use the Point Buy method for ability scores.',
      'Discussed and selected Origin feats for characters.',
      'Explored options for homebrew classes.',
      'Discussed incorporating appropriate jobs/classes fitting the setting.',
      'Set up level 3 characters.'
    ]
  },
  {
    id: 'session-minus-1',
    title: 'Session -1',
    subtitle: 'Initial world building and general framework discussions',
    date: 'April 6, 2025',
    description: 'Hopes, dreams and expectations setting. Discussed the world\'s themes, character concepts, and narrative boundaries.',
    highlights: [
      'Established our world as a Steampunk/Gaslamp Fantasy setting where magic and emerging technology exist in societal tension.',
      'Explored the possibility of an overarching church structure reminiscent of Catholicism, influencing the world\'s spiritual and political landscape.',
      'Discussed how our world\'s society is stratified between nobles and commoners, creating opportunities for diverse character backgrounds.',
      'Shared initial character concepts and considered how each might fit into different societal niches.',
      'Had conversations about narrative boundaries and player comfort zones.',
      'Contemplated whether characters will have pre-existing connections when our adventure begins.'
    ]
  }
];

export default sessions;