<template>
  <div class="content-section">
    <h1>World Lore</h1>
    <div class="lore-list">
      <!-- Add id attribute for scrolling -->
      <div v-for="(item, index) in loreData" :key="index" class="lore-item" :id="item.id">
        <h3 class="lore-term">{{ item.term }}</h3>
        <p class="lore-description" v-html="formatDescription(item.description)"></p>
        <!-- Add EntityConnections component -->
        <EntityConnections :entityType="'lore'" :entityId="item.id" />
      </div>
    </div>
  </div>
</template>

<script>
import { getLore } from '../store/worldData';
import { marked } from 'marked';
import EntityConnections from '../components/EntityConnections.vue'; // Import component

export default {
  name: 'LoreView',
  components: { // Register component
    EntityConnections
  },
  data() {
    return {
      loreData: getLore()
    };
  },
  methods: {
    formatDescription(description) {
      // Use marked to convert markdown (like blockquotes) to HTML
      return marked.parse(description || ''); // Changed from parseInline to parse
    }
  }
};
</script>

<style scoped>
.section-intro {
  text-align: center;
  max-width: 800px;
  margin: 0 auto 2em;
}

.lore-list {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.lore-item {
  background: var(--gradient-primary);
  border-radius: 8px;
  border: 1px solid var(--border-color);
  padding: 1.5rem;
  padding-bottom: 0;
  box-shadow: var(--shadow-sm);
  display: flex; /* Use flexbox for layout */
  flex-direction: column; /* Stack children vertically */
}

.lore-term {
  margin: 0 0 0.75rem 0;
  font-family: var(--font-display);
  color: var(--color-primary);
  font-size: 1.4rem;
}

.lore-description {
  margin: 0;
  line-height: 1.6;
  padding-bottom: 1em;;
}

/* Style for blockquotes generated by marked */
.lore-description :deep(blockquote) {
  margin-left: 1em;
  padding-left: 1em;
  border-left: 3px solid var(--color-accent);
  font-style: italic;
  color: var(--color-text-muted);
}

/* Style for italics generated by marked */
.lore-description :deep(em) {
  font-style: italic;
  color: var(--color-text-muted); /* Optional: style italics differently */
}
</style>
