<template>
  <div v-if="visible" class="modal-overlay" @click.self="closeModal">
    <div class="modal-content">
      <button class="close-button" @click="closeModal">&times;</button>
      <h2 v-if="title" class="modal-title">{{ title }}</h2> 
      
      <!-- Conditionally display image, loading indicator, or text -->
      <div v-if="imageUrl" class="modal-image-container">
        <img :src="imageUrl" :alt="title || 'Modal Image'" class="modal-image"/>
      </div>
      <div v-else-if="loading" class="loading-container">
        <div class="loading-spinner"></div>
        <p>Loading...</p>
      </div>
      <div v-else class="modal-body" :class="contentClass" v-html="renderContent(text)"></div>
      
    </div>
  </div>
</template>

<script>
import { marked } from 'marked'; // Import marked library

export default {
  name: 'FullTextModal',
  props: {
    visible: {
      type: Boolean,
      required: true
    },
    text: {
      type: String,
      default: ''
    },
    title: { // Add title prop
      type: String,
      default: ''
    },
    imageUrl: String, // Add imageUrl prop
    loading: { // Add loading prop
      type: Boolean,
      default: false
    },
    contentClass: { // Add contentClass prop for styling variants
      type: String,
      default: ''
    }
  },
  methods: {
    closeModal() {
      this.$emit('close');
    },
    renderContent(text) {
      if (!text) return '';
      // For transcript content, HTML is already formatted - pass through directly
      if (this.contentClass === 'transcript-content') {
        return text;
      }
      // Otherwise, render as markdown
      return this.renderMarkdown(text);
    },
    renderMarkdown(text) {
      if (!text) return '';
      // Basic markdown rendering with marked
      // Replace [[Link]] with actual links (assuming a specific routing logic)
      const linkedText = text.replace(/\[\[(.*?)\]\]/g, (match, p1) => {
        // This is a placeholder - you'll need to implement proper routing
        // based on your application's structure to link to the correct entity.
        const entityId = p1.toLowerCase().replace(/\s+/g, '-'); // Basic slugification
        // Example: Link to a generic entity page or specific view
        return `<a href="#/entity/${entityId}">${p1}</a>`; 
      });
      return marked(linkedText);
    }
  }
}
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.7);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-content {
  background-color: var(--color-background); /* Changed from --color-background-soft */
  padding: 2rem;
  border-radius: 8px;
  max-width: 900px; /* Changed from 80% */
  max-height: 90vh; /* Limit modal height */
  overflow-y: auto;
  position: relative;
  border: 1px solid var(--border-color);
  box-shadow: var(--shadow-lg);
  display: flex; /* Use flexbox for layout */
  flex-direction: column; /* Stack elements vertically */
}

.close-button {
  position: absolute;
  top: 1rem;
  right: 1rem;
  background: none;
  border: none;
  font-size: 1.8rem;
  color: var(--color-text-muted);
  cursor: pointer;
  line-height: 1;
}

/* Add these styles for tables */
.modal-body ::v-deep table {
  width: 100%;
  border-collapse: collapse;
  margin: 1em 0;
  font-size: 0.9em;
  font-family: var(--font-main);
}

.modal-body ::v-deep th,
.modal-body ::v-deep td {
  border: 1px solid var(--border-color);
  padding: 0.5em 1.75em 0.5em 0.75em; /* Added right padding */
  text-align: left;
}

.modal-body ::v-deep th {
  background-color: var(--color-background-soft); /* Or a slightly darker shade of your modal background */
  font-weight: bold;
  color: var(--color-heading);
}

.modal-body ::v-deep tr:nth-child(even) {
  background-color: var(--color-background-mute); /* For striped rows, if desired */
}
/* End of new table styles */

.modal-body {
  margin-top: 0; /* Remove top margin as title provides spacing */
  line-height: 1.7;
  overflow-y: auto; /* Allow scrolling for long text */
  flex-grow: 1; /* Allow text area to grow */
}

/* Style links generated by markdown */
.modal-body ::v-deep a {
  color: var(--color-accent);
  text-decoration: none;
  font-weight: bold;
}

.modal-body ::v-deep a:hover {
  text-decoration: underline;
}

/* Add styles for paragraphs, headings, etc. if needed */
.modal-body ::v-deep p {
  margin-bottom: 1em;
}

.modal-body ::v-deep h1,
.modal-body ::v-deep h2,
.modal-body ::v-deep h3 {
  margin-top: 1.5em;
  margin-bottom: 0.5em;
  color: var(--color-primary);
}

/* Title styling */
.modal-title {
  font-family: var(--font-display);
  color: var(--color-primary);
  margin: 0 0 1rem 0; /* Adjust margin */
  padding-bottom: 0.5rem;
  border-bottom: 1px solid var(--border-color);
  font-size: 1.6rem;
  line-height: 1.3;
}

.modal-image-container {
  text-align: center; /* Center the image */
  padding: 1rem 0; /* Add some padding */
  flex-grow: 1; /* Allow image container to grow */
  display: flex; /* Center image vertically */
  align-items: center; /* Center image vertically */
  justify-content: center; /* Center image horizontally */
}

.modal-image {
  max-width: 100%; /* Ensure image fits width */
  max-height: 70vh; /* Limit image height */
  height: auto; /* Maintain aspect ratio */
  display: block; /* Remove extra space below image */
  margin: 0 auto; /* Center horizontally if needed */
}

/* Loading styles */
.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 2rem;
  height: 200px;
}

.loading-spinner {
  width: 50px;
  height: 50px;
  border: 4px solid rgba(0, 0, 0, 0.1);
  border-radius: 50%;
  border-top-color: var(--color-primary);
  animation: spin 1s linear infinite;
  margin-bottom: 1rem;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

/* Transcript-specific styles */
.modal-body.transcript-content {
  font-family: var(--font-main);
  font-size: 0.9rem;
  line-height: 1.5;
  padding: 0;
}

/* Transcript line container */
.modal-body.transcript-content ::v-deep .transcript-line {
  display: flex;
  align-items: flex-start;
  padding: 0.3em 0.5em;
  border-radius: 4px;
  gap: 0.5em;
  transition: background-color 0.15s;
}

.modal-body.transcript-content ::v-deep .transcript-line:hover {
  background-color: var(--color-background-soft, rgba(255,255,255,0.05));
}

/* Add subtle separator when speaker changes */
.modal-body.transcript-content ::v-deep .transcript-line.new-speaker {
  margin-top: 0.6em;
  border-top: 1px solid var(--border-color, rgba(255,255,255,0.1));
  padding-top: 0.6em;
}

/* Avatar styling */
.modal-body.transcript-content ::v-deep .transcript-avatar {
  width: 22px;
  height: 22px;
  border-radius: 50%;
  object-fit: cover;
  flex-shrink: 0;
  border: 1px solid var(--border-color, rgba(255,255,255,0.2));
}

/* Placeholder for speakers without avatars (like GM) */
.modal-body.transcript-content ::v-deep .transcript-avatar-placeholder {
  width: 22px;
  height: 22px;
  border-radius: 50%;
  background: var(--color-background-mute, #444);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.7em;
  font-weight: bold;
  color: var(--text-muted, #888);
  flex-shrink: 0;
  border: 1px solid var(--border-color, rgba(255,255,255,0.2));
}

/* Timestamp styling */
.modal-body.transcript-content ::v-deep .transcript-timestamp {
  color: var(--text-muted, #666);
  font-size: 0.75em;
  font-family: var(--font-mono, monospace);
  opacity: 0.6;
  flex-shrink: 0;
  min-width: 55px;
}

/* Speaker name styling */
.modal-body.transcript-content ::v-deep .transcript-speaker {
  font-weight: 600;
  flex-shrink: 0;
  min-width: 80px;
}

/* Character-specific speaker colors - subtle nods to avatar color schemes */
.modal-body.transcript-content ::v-deep .transcript-speaker.speaker-gm {
  color: #e6a23c; /* Warm amber/orange for GM */
}

.modal-body.transcript-content ::v-deep .transcript-speaker.speaker-nyx {
  color: #9a8fbd; /* Muted purple/shadow - Shadar-kai */
}

.modal-body.transcript-content ::v-deep .transcript-speaker.speaker-ellara {
  color: #d4a855; /* Warm gold - Eulogian light/druid */
}

.modal-body.transcript-content ::v-deep .transcript-speaker.speaker-berridin {
  color: #c49a6c; /* Earthy tan/brown - Halfling */
}

.modal-body.transcript-content ::v-deep .transcript-speaker.speaker-ysidor {
  color: #7ba3c4; /* Cool blue/grey - Goliath/mountain */
}

.modal-body.transcript-content ::v-deep .transcript-speaker.speaker-tsinyra {
  color: #7cb587; /* Natural green - Genasi/nature */
}

.modal-body.transcript-content ::v-deep .transcript-speaker.speaker-witty {
  color: #b08dc9; /* Purple - his signature color */
}

.modal-body.transcript-content ::v-deep .transcript-speaker.speaker-unknown {
  color: var(--color-text-muted, #888);
}

/* Dialogue text */
.modal-body.transcript-content ::v-deep .transcript-text {
  color: var(--color-text, #ddd);
  flex: 1;
}

/* Plain text lines (non-dialogue) */
.modal-body.transcript-content ::v-deep .transcript-line.transcript-plain {
  color: var(--text-muted, #888);
  font-style: italic;
  padding-left: 2em;
}
</style>